services:
  - type: web
    name: jobbanglinainesfin
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
